[package]
name = "crarog"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = {version = "*", features = ["derive"]}
serde_json = "*"
clap = {version = "4.5.4", features = ["derive"]}
color-print = "0.3.6"
indicatif = "0.17.8"
